# Generated by Django 4.2 on 2024-04-09 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["name"],
                "verbose_name": "Фотографию",
                "verbose_name_plural": "Фотографии",
            },
        ),
    ]
